---
- name: Create AWS Directory
  file:
    path: "{{ jenkins_home }}/.aws/"
    state: directory
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0755

- name: Configure AWS CLI
  blockinfile:
    path: "{{ jenkins_home }}/.aws/config"
    state: present
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0644
    create: yes
    block: |
      [default]
      region = {{ aws_region }}
      output = json

- name: Copy .gitignore
  copy:
    src: gitignore
    dest: "{{ jenkins_home }}/.gitignore"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0644

- name: Configure Git
  blockinfile:
    path: "{{ jenkins_home }}/.gitconfig"
    state: present
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0644
    create: yes
    block: |
      [user]
        name = Jenkins
        email = jenkins@venicegeo.io
      [credential]
        helper = !aws --profile default codecommit credential-helper $@
        UseHttpPath = true
