- name: Download Java JDKs
  get_url:
    url: "{{ item }}"
    headers:
      Cookie: oraclelicense=accept-securebackup-cookie
    dest: /tmp
  with_items:
    - https://download.oracle.com/otn-pub/java/jdk/8u201-b09/42970487e3af4f5aa5bca3f542482c60/jdk-8u201-linux-x64.tar.gz
    - https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.3%2B7/OpenJDK11U-jdk_x64_linux_hotspot_11.0.3_7.tar.gz

- name: Ensure tools directory is present
  file:
    path: "{{ jenkins_home }}/tools"
    state: directory
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: u+rwx

- name: Copy JDKs into place
  unarchive:
    remote_src: yes
    src: "/tmp/{{ item }}"
    dest: "{{ jenkins_home }}/tools"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
  with_items:
    - "{{ jdk8_version }}-linux-x64.tar.gz"
    - "OpenJDK11U-jdk_x64_linux_hotspot_{{ jdk11_version }}.tar.gz"

- name: Remove JDKs downloads
  file:
    path: "/tmp/{{ item }}"
    state: absent
  with_items:
    - "{{ jdk8_version }}-linux-x64.tar.gz"
    - "OpenJDK11U-jdk_x64_linux_hotspot_{{ jdk11_version }}.tar.gz"
