- name: Download Java JDKs
  get_url:
    url: "{{ item }}"
    headers: "Cookie:oraclelicense=accept-securebackup-cookie"
    dest: /tmp
  with_items:
    - http://download.oracle.com/otn-pub/java/jdk/10.0.1+10/fb4372174a714e6b8c52526dc134031e/jdk-10.0.1_linux-x64_bin.tar.gz
    - http://download.oracle.com/otn-pub/java/jdk/8u172-b11/a58eab1ec242421181065cdc37240b08/jdk-8u172-linux-x64.tar.gz

- name: Ensure tools directory is present
  file:
    path: "{{ jenkins_home }}/tools"
    state: directory
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: u+rwx

- name: Copy JDKs into place
  unarchive:
    remote_src: yes
    src: "/tmp/{{ item }}"
    dest: "{{ jenkins_home }}/tools"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
  with_items:
    - jdk-10.0.1_linux-x64_bin.tar.gz
    - jdk-8u172-linux-x64.tar.gz
