- name: Download Java JDKs
  get_url:
    url: "{{ item }}"
    headers: "Cookie:oraclelicense=accept-securebackup-cookie"
    dest: /tmp
  with_items:
    - http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jdk-8u181-linux-x64.tar.gz
    - http://download.oracle.com/otn-pub/java/jdk/10.0.2+13/19aef61b38124481863b1413dce1855f/jdk-10.0.2_linux-x64_bin.tar.gz

- name: Ensure tools directory is present
  file:
    path: "{{ jenkins_home }}/tools"
    state: directory
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: u+rwx

- name: Copy JDK 8 into place
  unarchive:
    remote_src: yes
    src: "/tmp/{{ jdk8_version }}-linux-x64.tar.gz"
    dest: "{{ jenkins_home }}/tools/{{ jdk8_version }}/"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"

- name: Copy JDK 10 into place
  unarchive:
    remote_src: yes
    src: "/tmp/{{ jdk10_version }}_linux-x64_bin.tar.gz"
    dest: "{{ jenkins_home }}/tools/{{ jdk10_version }}/"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"

- name: Remove JDKs downloads
  file:
    path: "/tmp/{{ item }}"
    state: absent
  with_items:
    - "{{ jdk10_version }}_linux-x64_bin.tar.gz"
    - "{{ jdk8_version }}-linux-x64.tar.gz"
