- name: Copy Jenkins-Backup Job
  copy:
    src: config.xml
    dest: "{{ jenkins_home }}/jobs/jenkins-backup/"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775
  notify: restart jenkins
  when: create_backup_job

- name: Copy Job Configurations
  copy:
    src: "{{ jenkins_job_configs }}"
    dest: "{{ jenkins_home }}/jobs"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775
  when: jenkins_job_configs is defined
  notify: restart jenkins
