- name: Ensure nginx and letsencrypt are installed
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - nginx
    - python2-certbot-nginx

- name: Ensure pyopenssl is installed
  pip:
    name: pyopenssl
    state: latest

- name: Ensure SELinux boolean is set
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: Ensure required directories exist
  file:
    name: "{{ item }}"
    state: directory
    owner: nginx
    group: nginx
  with_items:
    - /var/www/letsencrypt
    - /etc/nginx/sites-enabled
    - /var/log/nginx

- name: Remove default nginx config
  file:
    name: /etc/nginx/sites-enabled/default
    state: absent

- name: Install system nginx config
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Install nginx site for letsencrypt requests
  template:
    src: templates/nginx-letsencrypt.j2
    dest: /etc/nginx/sites-enabled/letsencrypt

- name: Reload nginx to activate letsencrypt site
  service:
    name: nginx
    state: restarted

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
    privatekey_path: "/etc/letsencrypt/live/{{ domain_name }}/private/privkey.pem"
    csr_path: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
    provider: selfsigned

- name: Create letsencrypt certificate
  shell: letsencrypt -n -w /var/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos -d {{ domain_name }} --nginx
  args:
    creates: /etc/letsencrypt/live/{{ domain_name }}
  tags: [ 'never', 'gen_certificate' ]

- name: Generate dhparams
  shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem

- name: Install nginx site for specified site
  template:
    src: templates/nginx-jenkins.j2
    dest: /etc/nginx/sites-enabled/jenkins

- name: Reload nginx to activate specified site
  service:
    name: nginx
    state: restarted

- name: Add letsencrypt cronjob for cert renewal
  cron:
    name: letsencrypt_renewal
    special_time: weekly
    job: letsencrypt renew && service nginx reload
