- name: Ensure nginx and letsencrypt are installed
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - nginx
    - python2-certbot-nginx

- name: Ensure pyopenssl is installed
  pip:
    name: pyopenssl
    state: latest

- name: Ensure SELinux boolean is set
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  when: ansible_os_family == 'RedHat'

- name: Ensure required directories exist
  file:
    name: "{{ item }}"
    state: directory
  with_items:
    - /etc/nginx/sites-enabled
    - /var/log/nginx
    - "/etc/letsencrypt/live/{{ domain_name}}"

- name: Remove default nginx config
  file:
    name: /etc/nginx/sites-enabled/default
    state: absent

- name: Install system nginx config
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: create self-signed SSL cert
  command: "openssl req -new -nodes -x509 -subj /C=US/ST=Colorado/L=Westminster/O=IT/CN={{ domain_name }} -days 3650 -keyout /etc/letsencrypt/live/{{ domain_name }}/privkey.pem -out /etc/letsencrypt/live/{{ domain_name }}/fullchain.pem -extensions v3_ca"
  tags: gen_self_signed_cert

- name: Create letsencrypt certificate
  shell: letsencrypt -n -m {{ letsencrypt_email }} --agree-tos -d {{ domain_name }} --nginx
  args:
    creates: /etc/letsencrypt/live/{{ domain_name }}
  tags: gen_certificate

- name: Generate dhparams
  shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem

- name: Install nginx site for specified site
  template:
    src: templates/nginx-jenkins.j2
    dest: /etc/nginx/sites-enabled/jenkins

- name: Reload nginx to activate specified site
  service:
    name: nginx
    state: restarted
    enabled: true

- name: Add letsencrypt cronjob for cert renewal
  cron:
    name: letsencrypt_renewal
    special_time: weekly
    job: letsencrypt renew && service nginx reload
